import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

// Downtown Austin buildings dataset (all tiers)
const downtownBuildings = [
  // TIER 1 — Major High-Rise Residential / Mixed-Use Towers
  {
    name: "The Independent",
    address: "301 West Ave, Austin, TX 78701",
    district: "seaholm",
    tier: 1,
    type: "condo",
    lat: 30.2683,
    lng: -97.7495,
    units: 363,
    yearBuilt: 2019,
    priceTier: "luxury",
    walkScore: 98,
    perkDensity: 0.9,
    activityScore: 0.95,
    nearbyVenues: ["true_food_kitchen", "seaholm_cafe", "trader_joes"],
    tags: ["iconic", "high-rise", "jenga-tower", "skyline"]
  },
  {
    name: "The Austonian",
    address: "401 Colorado St, Austin, TX 78701",
    district: "cbd",
    tier: 1,
    type: "condo",
    lat: 30.2635,
    lng: -97.7468,
    units: 287,
    yearBuilt: 2010,
    priceTier: "luxury",
    walkScore: 97,
    perkDensity: 0.92,
    activityScore: 0.93,
    nearbyVenues: ["second_bar_kitchen", "uchi", "congress_ave"],
    tags: ["downtown-core", "high-rise", "central"]
  },
  {
    name: "360 Condominiums",
    address: "360 Nueces St, Austin, TX 78701",
    district: "cbd",
    tier: 1,
    type: "condo",
    lat: 30.2678,
    lng: -97.7466,
    units: 247,
    yearBuilt: 2006,
    priceTier: "luxury",
    walkScore: 97,
    perkDensity: 0.88,
    activityScore: 0.9,
    nearbyVenues: ["austin_saloon", "6th_street", "republic_square"],
    tags: ["historic", "central"]
  },
  {
    name: "5th & West Residences",
    address: "511 West Ave, Austin, TX 78701",
    district: "cbd",
    tier: 1,
    type: "mixed_use",
    lat: 30.2706,
    lng: -97.7495,
    units: 420,
    yearBuilt: 2018,
    priceTier: "luxury",
    walkScore: 99,
    perkDensity: 0.93,
    activityScore: 0.94,
    nearbyVenues: ["whole_foods", "west_lake", "zilker_park"],
    tags: ["mixed-use", "walkable", "flagship"]
  },
  {
    name: "The Ashton",
    address: "208 West 6th St, Austin, TX 78703",
    district: "cbd",
    tier: 1,
    type: "condo",
    lat: 30.2652,
    lng: -97.7498,
    units: 310,
    yearBuilt: 2008,
    priceTier: "luxury",
    walkScore: 98,
    perkDensity: 0.87,
    activityScore: 0.89,
    nearbyVenues: ["bar_none", "6th_street", "rainey_street"],
    tags: ["historic-core"]
  },
  {
    name: "The W Residences Austin",
    address: "200 Congress Ave, Austin, TX 78701",
    district: "cbd",
    tier: 1,
    type: "hotel_residential",
    lat: 30.2637,
    lng: -97.7412,
    units: 251,
    yearBuilt: 2005,
    priceTier: "luxury",
    walkScore: 99,
    perkDensity: 0.91,
    activityScore: 0.92,
    nearbyVenues: ["congress_ave_bars", "splash_pad", "downtown"],
    tags: ["hotel-residential", "congress-ave", "icon"]
  },
  {
    name: "Seaholm Residences",
    address: "500 North Shore Drive, Austin, TX 78701",
    district: "seaholm",
    tier: 1,
    type: "apartment",
    lat: 30.2709,
    lng: -97.7489,
    units: 401,
    yearBuilt: 2021,
    priceTier: "luxury",
    walkScore: 99,
    perkDensity: 0.96,
    activityScore: 0.97,
    nearbyVenues: ["seaholm_cafe", "seaholm_market", "flower_child"],
    tags: ["seaholm-core", "riverfront", "walkable"]
  },
  {
    name: "The Bowie",
    address: "1500 South Congress Ave, Austin, TX 78704",
    district: "warehouse",
    tier: 1,
    type: "condo",
    lat: 30.2534,
    lng: -97.7505,
    units: 240,
    yearBuilt: 2015,
    priceTier: "premium",
    walkScore: 94,
    perkDensity: 0.82,
    activityScore: 0.85,
    nearbyVenues: ["matt_franks", "south_congress", "barton_springs"],
    tags: ["south-congress", "trendy", "soco"]
  },
  {
    name: "The Catherine",
    address: "214 Barton Springs Rd, Austin, TX 78704",
    district: "rainey",
    tier: 1,
    type: "apartment",
    lat: 30.2553,
    lng: -97.7410,
    units: 300,
    yearBuilt: 2015,
    priceTier: "premium",
    walkScore: 93,
    perkDensity: 0.85,
    activityScore: 0.9,
    nearbyVenues: ["cosmic_saltillo", "eastciders", "barton_springs"],
    tags: ["riverfront", "barton-springs"]
  },
  {
    name: "70 Rainey",
    address: "70 Rainey St, Austin, TX 78701",
    district: "rainey",
    tier: 1,
    type: "condo",
    lat: 30.2566,
    lng: -97.7380,
    units: 289,
    yearBuilt: 2017,
    priceTier: "luxury",
    walkScore: 96,
    perkDensity: 0.94,
    activityScore: 0.98,
    nearbyVenues: ["rainey_bars", "lustre_pearl", "half_step"],
    tags: ["rainey-core", "nightlife", "walkable"]
  },
  {
    name: "Milago Condominiums",
    address: "98 Rainey St, Austin, TX 78701",
    district: "rainey",
    tier: 1,
    type: "condo",
    lat: 30.2572,
    lng: -97.7375,
    units: 267,
    yearBuilt: 2012,
    priceTier: "luxury",
    walkScore: 96,
    perkDensity: 0.95,
    activityScore: 0.99,
    nearbyVenues: ["geraldines", "suki_sushi", "rainey_pavilion"],
    tags: ["rainey-core", "nightlife"]
  },
  {
    name: "The Shore",
    address: "98 East Ave, Austin, TX 78704",
    district: "rainey",
    tier: 1,
    type: "apartment",
    lat: 30.2555,
    lng: -97.7390,
    units: 318,
    yearBuilt: 2016,
    priceTier: "premium",
    walkScore: 95,
    perkDensity: 0.93,
    activityScore: 0.96,
    nearbyVenues: ["east_sixth", "rain_on_4th", "barton_springs"],
    tags: ["rainey-district", "riverfront"]
  },
  {
    name: "Vesper Austin",
    address: "500 West Avenue, Austin, TX 78701",
    district: "seaholm",
    tier: 1,
    type: "condo",
    lat: 30.2710,
    lng: -97.7494,
    units: 278,
    yearBuilt: 2020,
    priceTier: "luxury",
    walkScore: 99,
    perkDensity: 0.94,
    activityScore: 0.95,
    nearbyVenues: ["seaholm_retail", "whole_foods", "trader_joes"],
    tags: ["seaholm", "luxury", "modern"]
  },
  {
    name: "The Modern Austin Residences",
    address: "611 West 6th St, Austin, TX 78701",
    district: "cbd",
    tier: 1,
    type: "condo",
    lat: 30.2666,
    lng: -97.7516,
    units: 224,
    yearBuilt: 2014,
    priceTier: "premium",
    walkScore: 97,
    perkDensity: 0.86,
    activityScore: 0.88,
    nearbyVenues: ["barton_springs", "zilker_park", "lady_bird_lake"],
    tags: ["west-downtown", "modern"]
  },
  {
    name: "The Quincy",
    address: "101 Congress Ave, Austin, TX 78701",
    district: "cbd",
    tier: 1,
    type: "condo",
    lat: 30.2617,
    lng: -97.7408,
    units: 195,
    yearBuilt: 2009,
    priceTier: "luxury",
    walkScore: 99,
    perkDensity: 0.89,
    activityScore: 0.91,
    nearbyVenues: ["congress_ave", "lady_bird_lake", "zilker_park"],
    tags: ["congress-core", "downtown"]
  },
  {
    name: "The Linden Residences",
    address: "500 Meaning St, Austin, TX 78704",
    district: "rainey",
    tier: 1,
    type: "apartment",
    lat: 30.2545,
    lng: -97.7395,
    units: 278,
    yearBuilt: 2018,
    priceTier: "premium",
    walkScore: 94,
    perkDensity: 0.88,
    activityScore: 0.92,
    nearbyVenues: ["rainey_street", "east_sixth", "barton_springs"],
    tags: ["rainey-adjacent"]
  },
  {
    name: "Residences at 6G",
    address: "600 Guadalupe St, Austin, TX 78701",
    district: "cbd",
    tier: 1,
    type: "mixed_use",
    lat: 30.2687,
    lng: -97.7424,
    units: 356,
    yearBuilt: 2019,
    priceTier: "luxury",
    walkScore: 98,
    perkDensity: 0.90,
    activityScore: 0.92,
    nearbyVenues: ["ut_campus", "guadalupe_street", "university"],
    tags: ["ut-adjacent", "student-friendly"]
  },

  // TIER 2 — Rainey Street District
  {
    name: "44 East Ave",
    address: "44 East Ave, Austin, TX 78704",
    district: "rainey",
    tier: 2,
    type: "condo",
    lat: 30.2559,
    lng: -97.7384,
    units: 309,
    yearBuilt: 2022,
    priceTier: "luxury",
    walkScore: 95,
    perkDensity: 0.95,
    activityScore: 1,
    nearbyVenues: ["lustre_pearl", "geraldines", "half_step", "suki_sushi"],
    tags: ["rainey-core", "new", "walkable"]
  },
  {
    name: "48 East Ave",
    address: "48 East Ave, Austin, TX 78704",
    district: "rainey",
    tier: 2,
    type: "apartment",
    lat: 30.2558,
    lng: -97.7382,
    units: 287,
    yearBuilt: 2021,
    priceTier: "premium",
    walkScore: 95,
    perkDensity: 0.94,
    activityScore: 0.99,
    nearbyVenues: ["rainey_street", "east_sixth", "barton_springs"],
    tags: ["rainey-core", "new"]
  },
  {
    name: "Natiivo Austin",
    address: "97 Rainey St, Austin, TX 78701",
    district: "rainey",
    tier: 2,
    type: "mixed_use",
    lat: 30.2570,
    lng: -97.7378,
    units: 224,
    yearBuilt: 2019,
    priceTier: "luxury",
    walkScore: 96,
    perkDensity: 0.96,
    activityScore: 1,
    nearbyVenues: ["rainey_pavilion", "suki_sushi", "lustre_pearl"],
    tags: ["rainey-core", "mixed-use", "nightlife"]
  },
  {
    name: "The Travis",
    address: "98 East Ave, Austin, TX 78704",
    district: "rainey",
    tier: 2,
    type: "apartment",
    lat: 30.2556,
    lng: -97.7386,
    units: 256,
    yearBuilt: 2017,
    priceTier: "premium",
    walkScore: 94,
    perkDensity: 0.92,
    activityScore: 0.97,
    nearbyVenues: ["geraldines", "half_step", "barton_springs"],
    tags: ["rainey-district"]
  },
  {
    name: "RiverStreet Residences",
    address: "210 Lavaca St, Austin, TX 78701",
    district: "rainey",
    tier: 2,
    type: "apartment",
    lat: 30.2575,
    lng: -97.7398,
    units: 298,
    yearBuilt: 2016,
    priceTier: "premium",
    walkScore: 93,
    perkDensity: 0.90,
    activityScore: 0.94,
    nearbyVenues: ["rain_on_4th", "rainey_street", "barton_springs"],
    tags: ["rainey-adjacent", "riverfront"]
  },
  {
    name: "Hanover Republic Square",
    address: "400 Colorado St, Austin, TX 78701",
    district: "cbd",
    tier: 2,
    type: "apartment",
    lat: 30.2635,
    lng: -97.7438,
    units: 341,
    yearBuilt: 2020,
    priceTier: "premium",
    walkScore: 98,
    perkDensity: 0.89,
    activityScore: 0.91,
    nearbyVenues: ["republic_square_park", "congress_avenue", "downtown"],
    tags: ["downtown-core", "park-adjacent"]
  },

  // TIER 3 — West End / Market District / Seaholm
  {
    name: "The Clark",
    address: "150 West 2nd St, Austin, TX 78701",
    district: "market_district",
    tier: 3,
    type: "apartment",
    lat: 30.2588,
    lng: -97.7412,
    units: 263,
    yearBuilt: 2014,
    priceTier: "mid",
    walkScore: 93,
    perkDensity: 0.85,
    activityScore: 0.88,
    nearbyVenues: ["2nd_street", "barton_springs", "lady_bird_lake"],
    tags: ["market-district", "walkable"]
  },
  {
    name: "The Waller",
    address: "100 Waller St, Austin, TX 78701",
    district: "market_district",
    tier: 3,
    type: "apartment",
    lat: 30.2603,
    lng: -97.7376,
    units: 220,
    yearBuilt: 2013,
    priceTier: "mid",
    walkScore: 92,
    perkDensity: 0.82,
    activityScore: 0.86,
    nearbyVenues: ["waller_street", "rainey_adjacent", "downtown"],
    tags: ["market-district"]
  },
  {
    name: "AMLI on 2nd",
    address: "350 West 2nd St, Austin, TX 78701",
    district: "west_end",
    tier: 3,
    type: "apartment",
    lat: 30.2599,
    lng: -97.7461,
    units: 378,
    yearBuilt: 2018,
    priceTier: "premium",
    walkScore: 95,
    perkDensity: 0.88,
    activityScore: 0.90,
    nearbyVenues: ["zilker_park", "west_lake", "lady_bird_lake"],
    tags: ["west-end", "walkable"]
  },
  {
    name: "AMLI Downtown",
    address: "404 Colorado St, Austin, TX 78701",
    district: "cbd",
    tier: 3,
    type: "apartment",
    lat: 30.2637,
    lng: -97.7437,
    units: 325,
    yearBuilt: 2017,
    priceTier: "premium",
    walkScore: 97,
    perkDensity: 0.87,
    activityScore: 0.89,
    nearbyVenues: ["congress_avenue", "republic_square", "downtown"],
    tags: ["downtown-core"]
  },
  {
    name: "Gables Park Tower",
    address: "2200 Barton Ave, Austin, TX 78704",
    district: "west_end",
    tier: 3,
    type: "apartment",
    lat: 30.2530,
    lng: -97.7570,
    units: 445,
    yearBuilt: 2015,
    priceTier: "mid",
    walkScore: 88,
    perkDensity: 0.78,
    activityScore: 0.82,
    nearbyVenues: ["zilker_park", "barton_springs_pool", "south_austin"],
    tags: ["zilker-adjacent", "large-complex"]
  },
  {
    name: "Gables Park Plaza",
    address: "2200 Barton Ave, Austin, TX 78704",
    district: "west_end",
    tier: 3,
    type: "apartment",
    lat: 30.2528,
    lng: -97.7572,
    units: 389,
    yearBuilt: 2016,
    priceTier: "mid",
    walkScore: 88,
    perkDensity: 0.78,
    activityScore: 0.81,
    nearbyVenues: ["zilker_park", "barton_springs", "west_lake_hills"],
    tags: ["zilker-adjacent", "large-complex"]
  },
  {
    name: "Northshore",
    address: "110 San Antonio St, Austin, TX 78701",
    district: "seaholm",
    tier: 3,
    type: "apartment",
    lat: 30.2695,
    lng: -97.7506,
    units: 439,
    yearBuilt: 2016,
    priceTier: "premium",
    walkScore: 99,
    perkDensity: 0.95,
    activityScore: 0.92,
    nearbyVenues: ["flower_child", "tacodeli", "whole_foods"],
    tags: ["seaholm", "mixed-use", "walkable"]
  },
  {
    name: "Spring Condominiums",
    address: "450 West 1st St, Austin, TX 78701",
    district: "west_end",
    tier: 3,
    type: "condo",
    lat: 30.2566,
    lng: -97.7435,
    units: 187,
    yearBuilt: 2011,
    priceTier: "mid",
    walkScore: 91,
    perkDensity: 0.80,
    activityScore: 0.83,
    nearbyVenues: ["west_1st_street", "lady_bird_lake", "barton_springs"],
    tags: ["west-end", "loft-style"]
  },

  // TIER 4 — Boutique / Mid-Rise / Loft Conversions
  {
    name: "Austin City Lofts",
    address: "916 East 6th St, Austin, TX 78702",
    district: "red_river",
    tier: 4,
    type: "loft",
    lat: 30.2665,
    lng: -97.7308,
    units: 156,
    yearBuilt: 2005,
    priceTier: "mid",
    walkScore: 91,
    perkDensity: 0.76,
    activityScore: 0.80,
    nearbyVenues: ["east_6th_street", "red_river", "live_music"],
    tags: ["red-river", "historic", "loft", "music-district"]
  },
  {
    name: "Avenue Lofts",
    address: "1301 Lavaca St, Austin, TX 78701",
    district: "market_district",
    tier: 4,
    type: "loft",
    lat: 30.2622,
    lng: -97.7412,
    units: 142,
    yearBuilt: 2007,
    priceTier: "mid",
    walkScore: 90,
    perkDensity: 0.75,
    activityScore: 0.78,
    nearbyVenues: ["lavaca_street", "barton_springs", "museum"],
    tags: ["market-district", "historic", "loft"]
  },
  {
    name: "Brazos Place",
    address: "901 East 6th St, Austin, TX 78702",
    district: "red_river",
    tier: 4,
    type: "loft",
    lat: 30.2661,
    lng: -97.7312,
    units: 128,
    yearBuilt: 2004,
    priceTier: "mid",
    walkScore: 90,
    perkDensity: 0.74,
    activityScore: 0.79,
    nearbyVenues: ["red_river_district", "live_music", "restaurants"],
    tags: ["red-river", "loft", "music-district"]
  },
  {
    name: "Nokonah Condominiums",
    address: "1801 E 6th St, Austin, TX 78702",
    district: "red_river",
    tier: 4,
    type: "condo",
    lat: 30.2675,
    lng: -97.7288,
    units: 115,
    yearBuilt: 2003,
    priceTier: "mid",
    walkScore: 89,
    perkDensity: 0.72,
    activityScore: 0.76,
    nearbyVenues: ["red_river", "east_6th", "cultural_district"],
    tags: ["red-river", "boutique"]
  },
  {
    name: "Sabine on Fifth",
    address: "510 Sabine St, Austin, TX 78701",
    district: "cbd",
    tier: 4,
    type: "loft",
    lat: 30.2656,
    lng: -97.7390,
    units: 98,
    yearBuilt: 2006,
    priceTier: "mid",
    walkScore: 93,
    perkDensity: 0.77,
    activityScore: 0.81,
    nearbyVenues: ["5th_street", "downtown_bars", "rainey_adjacent"],
    tags: ["downtown", "loft", "walkable"]
  },
  {
    name: "904 West Ave",
    address: "904 West Ave, Austin, TX 78703",
    district: "west_end",
    tier: 4,
    type: "loft",
    lat: 30.2737,
    lng: -97.7496,
    units: 87,
    yearBuilt: 2008,
    priceTier: "mid",
    walkScore: 92,
    perkDensity: 0.75,
    activityScore: 0.79,
    nearbyVenues: ["west_avenue", "zilker_park", "lady_bird_lake"],
    tags: ["west-end", "loft", "historic"]
  },
  {
    name: "Westgate Tower",
    address: "2601 Guadalupe St, Austin, TX 78705",
    district: "cbd",
    tier: 4,
    type: "condo",
    lat: 30.2863,
    lng: -97.7408,
    units: 201,
    yearBuilt: 1980,
    priceTier: "mid",
    walkScore: 88,
    perkDensity: 0.71,
    activityScore: 0.75,
    nearbyVenues: ["ut_campus", "guadalupe_street", "university"],
    tags: ["ut-adjacent", "vintage", "budget-friendly"]
  }
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Admin access required' }, { status: 403 });
    }

    // Seed all buildings
    const created = await base44.entities.Building.bulkCreate(downtownBuildings);

    return Response.json({
      success: true,
      count: created.length,
      message: `Successfully seeded ${created.length} downtown Austin buildings`,
      tiers: {
        tier1: downtownBuildings.filter(b => b.tier === 1).length,
        tier2: downtownBuildings.filter(b => b.tier === 2).length,
        tier3: downtownBuildings.filter(b => b.tier === 3).length,
        tier4: downtownBuildings.filter(b => b.tier === 4).length
      }
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});