import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  Building2,
  CalendarDays,
  Database,
  FileText,
  Megaphone,
  MessageSquare,
  ShieldCheck,
  ShoppingBag,
  Ticket,
  Users,
  Workflow,
} from 'lucide-react';
import type { EnterpriseComponent, PlatformDomain } from './types';

export const platformDomains: PlatformDomain[] = [
  {
    id: 'identity',
    route: '/admin',
    productName: 'Identity Layer',
    label: 'Identity',
    positioning: 'The access and tenant model for the full platform.',
    purpose: 'Controls users, organizations, buildings, roles, permissions, and workspace membership before any module can act on data.',
    icon: ShieldCheck,
    capabilities: ['data_model', 'workflow', 'permissions', 'api', 'analytics'],
    coreObjects: ['User', 'Role', 'Permission', 'Organization', 'Organization Membership', 'Building', 'Workspace Invite', 'Audit Log'],
    states: ['Invited', 'Active', 'Suspended', 'Revoked'],
    lifecycle: ['Invite Sent', 'Account Created', 'Workspace Joined', 'Role Assigned', 'Access Audited'],
    workflows: ['Workspace switching', 'Role-based access checks', 'Partner invitation routing', 'Building-scoped permissions'],
    permissions: ['owner', 'admin', 'manager', 'editor', 'analyst', 'viewer'],
    analytics: ['Active users', 'Workspace count', 'Invitation conversion', 'Permission changes', 'Audit volume'],
    apiSurface: ['/api/auth/me', '/api/entities/User', '/api/platform'],
    automations: [
      {
        trigger: 'Workspace invite accepted',
        condition: 'Invite token is valid',
        action: 'Create membership and assign role',
        notification: 'Notify workspace owner',
        auditLog: 'workspace_membership_created',
      },
    ],
    agent: {
      name: 'Access Agent',
      responsibilities: ['Explain permission gaps', 'Detect inactive members', 'Recommend role changes', 'Summarize audit activity'],
      examplePrompts: ['Who has access to this workspace?', 'Which roles changed this month?'],
    },
  },
  {
    id: 'property',
    route: '/admin/properties',
    productName: 'Property Operations Workspace',
    label: 'Properties',
    positioning: 'A building amenity people actually use.',
    purpose: 'Runs the building lifecycle from property setup through resident activation, partner relationships, reporting, and retention signals.',
    icon: Building2,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Property', 'Building', 'Unit', 'Resident', 'Staff Member', 'Access Point', 'Amenity', 'Partner Relationship', 'Campaign', 'Survey'],
    states: ['Draft', 'Configured', 'Launching', 'Active', 'Paused', 'Archived'],
    lifecycle: ['Building Created', 'Units Created', 'Residents Imported', 'QR Generated', 'Perks Activated', 'Events Activated', 'Reporting Activated'],
    workflows: ['Building onboarding', 'Unit inventory', 'Resident import', 'QR onboarding', 'Monthly building report'],
    permissions: ['owner', 'admin', 'manager', 'analyst', 'viewer'],
    analytics: ['Occupancy', 'Enrollment gap', 'Amenity utilization', 'Resident retention', 'Partner opportunity score'],
    apiSurface: ['/api/properties', '/api/entities/Building', '/api/entities/Flat', '/api/functions/generatePDFReport'],
    automations: [
      {
        trigger: 'Building joins',
        condition: 'Building has active status',
        action: 'Generate welcome campaign',
        notification: 'Notify property manager',
        auditLog: 'building_welcome_campaign_created',
      },
      {
        trigger: 'New perk added',
        condition: 'Perk is eligible for building',
        action: 'Notify building residents',
        notification: 'Send resident broadcast',
        auditLog: 'building_perk_notification_sent',
      },
    ],
    agent: {
      name: 'Property Agent',
      responsibilities: ['Occupancy analysis', 'Resident enrollment gaps', 'Partner opportunities', 'Amenity utilization', 'Resident retention insights', 'Monthly building reports'],
      examplePrompts: ['Which building has the biggest enrollment gap?', 'What should this property promote next month?'],
    },
  },
  {
    id: 'resident',
    route: '/admin/residents',
    productName: 'Resident CRM',
    label: 'Residents',
    positioning: 'A complete resident operating record.',
    purpose: 'Tracks membership, card access, events, perks, survey responses, engagement history, and retention scoring for every resident.',
    icon: Users,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Resident', 'Unit', 'Membership', 'Card', 'Perks', 'Events', 'Survey Responses', 'Engagement History'],
    states: ['Invited', 'Registered', 'Active', 'Inactive', 'Cancelled', 'Expired'],
    lifecycle: ['Resident Joins', 'Card Generated', 'Perks Activated', 'Engagement Tracking', 'Retention Scoring'],
    workflows: ['Resident import', 'Bulk updates', 'Card activation', 'Segment assignment', 'Retention outreach'],
    permissions: ['owner', 'admin', 'manager', 'editor', 'analyst', 'viewer'],
    analytics: ['Activation rate', 'Engagement level', 'Inactive residents', 'Retention score', 'Perk usage', 'Event participation'],
    apiSurface: ['/api/entities/Tenant', '/api/entities/Flat', '/api/functions/bulkUpdateResidents'],
    automations: [
      {
        trigger: 'New resident imported',
        condition: 'Resident record is valid',
        action: 'Create resident record and activation status',
        notification: 'Notify building manager',
        auditLog: 'resident_imported',
      },
      {
        trigger: 'Resident moves out',
        condition: 'Membership status is expired or cancelled',
        action: 'Disable resident card',
        notification: 'Notify property manager',
        auditLog: 'resident_card_disabled',
      },
    ],
    agent: {
      name: 'Resident Agent',
      responsibilities: ['Recommend events', 'Recommend perks', 'Predict churn', 'Identify high-value residents', 'Detect inactive members', 'Generate personalized messages'],
      examplePrompts: ['Which residents need reactivation?', 'Draft a message for residents who have not used perks.'],
    },
  },
  {
    id: 'partner',
    route: '/admin/partner-portal',
    productName: 'Partner CRM',
    label: 'Partner OS',
    positioning: 'Show up while people are choosing.',
    purpose: 'Gives partners a full workspace for locations, offers, campaigns, messaging, redemptions, reports, billing, and performance recommendations.',
    icon: ShoppingBag,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Partner', 'Location', 'Offer', 'Campaign', 'Message', 'Report', 'Redemption', 'Invoice'],
    states: ['Unlinked', 'Trial', 'Active', 'Suspended', 'Archived'],
    lifecycle: ['Partner Registered', 'Payment Confirmed', 'Workspace Activated', 'Offer Published', 'Reporting Enabled'],
    workflows: ['Partner signup', 'Workspace activation', 'Offer management', 'Campaign launch', 'Monthly report generation'],
    permissions: ['owner', 'admin', 'manager', 'editor', 'analyst', 'viewer', 'partner'],
    analytics: ['Active partners', 'Total redemptions', 'Unique customers', 'Top offer', 'Best day', 'Month-over-month change'],
    apiSurface: ['/api/entities/Partner', '/api/entities/PartnerMessage', '/api/functions/generatePartnerMonthlyReport'],
    automations: [
      {
        trigger: 'Partner submits registration',
        condition: 'Payment or review path is confirmed',
        action: 'Create workspace shell and selected plan context',
        notification: 'Notify partner success',
        auditLog: 'partner_workspace_created',
      },
    ],
    agent: {
      name: 'Partner Success Agent',
      responsibilities: ['Suggest new offers', 'Analyze redemption trends', 'Generate monthly reports', 'Draft campaigns', 'Recommend timing'],
      examplePrompts: ['What offer should this partner run next?', 'Summarize this partner performance for the month.'],
    },
  },
  {
    id: 'perks',
    route: '/admin/perks',
    productName: 'Offer Management System',
    label: 'Perks Network',
    positioning: 'Offer operations for the local network.',
    purpose: 'Manages offers, venues, categories, validity, redemption rules, inventory, review state, eligibility, and abuse monitoring.',
    icon: Ticket,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Offer', 'Venue', 'Category', 'District', 'Validity', 'Redemption Rules', 'Status', 'Inventory'],
    states: ['Draft', 'Pending Review', 'Active', 'Paused', 'Expired', 'Archived'],
    lifecycle: ['Offer Drafted', 'Eligibility Set', 'Review Approved', 'Published', 'Redeemed', 'Performance Optimized'],
    workflows: ['Offer review', 'QR redemption', 'Duplicate protection', 'Eligibility checks', 'Inventory monitoring'],
    permissions: ['owner', 'admin', 'manager', 'editor', 'analyst', 'partner'],
    analytics: ['Offer views', 'Saves', 'Directions', 'Redemptions', 'Conversion rate', 'Abuse flags'],
    apiSurface: ['/api/perks', '/api/entities/PerkLocation', '/api/functions/verifyRedemption'],
    automations: [
      {
        trigger: 'Card scan',
        condition: 'Offer is active and resident is eligible',
        action: 'Create redemption and update analytics',
        notification: 'Show verification state',
        auditLog: 'perk_redemption_created',
      },
    ],
    agent: {
      name: 'Perks Optimization Agent',
      responsibilities: ['Detect underperforming offers', 'Recommend new categories', 'Suggest timing', 'Monitor abuse', 'Optimize conversions'],
      examplePrompts: ['Which perks are underperforming?', 'Which category should we add next?'],
    },
  },
  {
    id: 'events',
    route: '/admin/events',
    productName: 'Community Programming Platform',
    label: 'Events OS',
    positioning: 'Things worth showing up for.',
    purpose: 'Runs event publishing, RSVP, attendance, surveys, sponsor matching, calendar sync, and post-event reporting.',
    icon: CalendarDays,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Event', 'Venue', 'Organizer', 'RSVP', 'Attendance', 'Survey', 'Sponsor'],
    states: ['Draft', 'Published', 'RSVP Open', 'In Progress', 'Completed', 'Reported', 'Archived'],
    lifecycle: ['Event Created', 'Published', 'RSVP Open', 'Attendance Tracking', 'Survey Sent', 'Performance Report'],
    workflows: ['Event creation', 'RSVP management', 'Calendar sync', 'Attendance tracking', 'Post-event survey'],
    permissions: ['owner', 'admin', 'manager', 'editor', 'analyst', 'viewer'],
    analytics: ['RSVPs', 'Attendance', 'No-show rate', 'Survey sentiment', 'Sponsor value', 'Repeat attendance'],
    apiSurface: ['/api/entities/Event', '/api/entities/EventRSVP', '/api/functions/syncBuildingEventsToCalendar'],
    automations: [
      {
        trigger: 'Event completed',
        condition: 'Attendance data exists',
        action: 'Send post-event survey and generate report',
        notification: 'Notify event owner',
        auditLog: 'event_report_generated',
      },
    ],
    agent: {
      name: 'Event Agent',
      responsibilities: ['Attendance forecasting', 'Event recommendations', 'RSVP prediction', 'Sponsor matching', 'Post-event analysis'],
      examplePrompts: ['Which event underperformed?', 'What should we schedule next weekend?'],
    },
  },
  {
    id: 'engagement',
    route: '/admin/engagement',
    productName: 'Resident Marketing Platform',
    label: 'Notes to send',
    positioning: 'Audience, campaigns, notifications, and journeys.',
    purpose: 'Combines audience building, segmentation, messaging, notifications, broadcasts, and journey orchestration across buildings and partner activity.',
    icon: Megaphone,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Audience', 'Segment', 'Campaign', 'Message', 'Notification', 'Broadcast', 'Journey'],
    states: ['Draft', 'Scheduled', 'Sending', 'Sent', 'Optimizing', 'Archived'],
    lifecycle: ['Audience Built', 'Segment Selected', 'Message Drafted', 'Scheduled', 'Sent', 'Measured', 'Optimized'],
    workflows: ['Audience builder', 'Segment targeting', 'Campaign drafting', 'Broadcast sending', 'Journey triggers'],
    permissions: ['owner', 'admin', 'manager', 'editor', 'analyst'],
    analytics: ['Reach', 'Open rate', 'Click rate', 'Saves', 'Redemptions influenced', 'Unsubscribes'],
    apiSurface: ['/api/entities/Broadcast', '/api/entities/Campaign', '/api/functions/sendBroadcast'],
    automations: [
      {
        trigger: 'Resident segment becomes inactive',
        condition: 'No event, perk, or map activity for threshold',
        action: 'Create reactivation journey',
        notification: 'Notify engagement manager',
        auditLog: 'resident_reactivation_journey_created',
      },
    ],
    agent: {
      name: 'Engagement Agent',
      responsibilities: ['Create segments', 'Generate campaigns', 'Recommend send times', 'Write messages', 'Optimize engagement'],
      examplePrompts: ['Create a segment for high-engagement residents.', 'Write a weekend event broadcast.'],
    },
  },
  {
    id: 'survey',
    route: '/admin/surveys',
    productName: 'Community Intelligence Platform',
    label: 'Survey OS',
    positioning: 'Ask better local questions and turn answers into action.',
    purpose: 'Connects resident, building, event, perk, NPS, and poll feedback to Tally/Jotform forms, Twilio messaging, CRM segments, exports, notifications, retry logs, and insight generation.',
    icon: MessageSquare,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Survey', 'Survey Provider Form', 'Survey Response', 'Question', 'Answer', 'CRM Segment', 'Messaging Journey', 'Export Log', 'Management Notification', 'Suggestion'],
    states: ['Draft', 'Distributed', 'Collecting', 'Completed', 'Analyzed', 'Escalated', 'Archived'],
    lifecycle: ['Survey Created', 'Provider Form Connected', 'Webhook Received', 'Response Stored', 'CRM Segment Updated', 'Message Journey Triggered', 'Insights Generated'],
    workflows: ['Tally resident onboarding', 'Perk redemption feedback', 'Event feedback', 'Twilio reminders', 'Google Sheets export', 'n8n webhook routing', 'Management escalation'],
    permissions: ['owner', 'admin', 'manager', 'editor', 'analyst', 'viewer'],
    analytics: ['Completion rate', 'NPS', 'Sentiment', 'Themes', 'Escalations', 'Response count'],
    apiSurface: ['/api/entities/Survey', '/api/entities/SurveyProviderForm', '/api/entities/SurveyResponse', '/api/entities/MessagingJourney', '/api/entities/AutomationRun', '/api/functions/processSurveyResponse'],
    automations: [
      {
        trigger: 'Resident completes survey or Tally/Jotform webhook is received',
        condition: 'NPS is below 6',
        action: 'Store response, update report row, create summary, and create follow-up task',
        notification: 'Notify property manager',
        auditLog: 'survey_escalation_created',
      },
      {
        trigger: 'Event RSVP or passport stamp created',
        condition: 'Resident phone is verified',
        action: 'Send Twilio reminder, progress message, or post-event survey link',
        notification: 'Log message delivery status',
        auditLog: 'messaging_journey_triggered',
      },
    ],
    agent: {
      name: 'Survey Intelligence Agent',
      responsibilities: ['Summarize responses', 'Detect themes', 'Generate insights', 'Find sentiment', 'Recommend actions', 'Create CRM segments', 'Prepare Twilio follow-up copy'],
      examplePrompts: ['Summarize this survey.', 'What actions should the property take from these responses?', 'Which residents should receive the next feedback journey?'],
    },
  },
  {
    id: 'reporting',
    route: '/admin/reports',
    productName: 'Report Generation System',
    label: 'Reports',
    positioning: 'Export-ready reporting across every operating loop.',
    purpose: 'Generates PDF, CSV, Excel, partner, building, campaign, and event reports with executive summaries and scheduled delivery.',
    icon: FileText,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Report', 'Report Template', 'Export', 'Schedule', 'Recipient', 'Attachment', 'Delivery Log'],
    states: ['Requested', 'Generating', 'Ready', 'Delivered', 'Failed', 'Archived'],
    lifecycle: ['Report Requested', 'Data Resolved', 'Generated', 'Delivered', 'Logged'],
    workflows: ['PDF export', 'CSV export', 'Weekly partner summary', 'Monthly building report', 'Board report'],
    permissions: ['owner', 'admin', 'manager', 'analyst', 'viewer'],
    analytics: ['Reports generated', 'Delivery success', 'Export failures', 'Report usage', 'Schedule health'],
    apiSurface: ['/api/functions/generatePDFReport', '/api/functions/sendWeeklyPartnerSummary', '/api/reports/:file'],
    automations: [
      {
        trigger: 'Monday 9:00 AM',
        condition: 'Resident engagement spreadsheet is connected',
        action: 'Append weekly resident and partner summary',
        notification: 'Notify operations team',
        auditLog: 'weekly_engagement_export_completed',
      },
    ],
    agent: {
      name: 'Reporting Agent',
      responsibilities: ['Generate executive summaries', 'Create monthly reports', 'Generate partner updates', 'Create building reports', 'Build board reports'],
      examplePrompts: ['Generate a monthly partner summary.', 'Create a board-ready building report.'],
    },
  },
  {
    id: 'analytics',
    route: '/admin/analytics',
    productName: 'Downtown Analytics',
    label: 'Analytics',
    positioning: 'The source of truth for participation, activity, and performance.',
    purpose: 'Aggregates residents, buildings, partners, events, offers, redemptions, engagement, and surveys into one KPI engine.',
    icon: BarChart3,
    capabilities: ['data_model', 'workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Metric', 'Event Stream', 'KPI', 'Dashboard', 'Segment', 'Warehouse Table', 'Insight'],
    states: ['Collecting', 'Processing', 'Ready', 'Flagged', 'Archived'],
    lifecycle: ['Event Captured', 'Data Normalized', 'Metric Updated', 'Insight Generated', 'Action Recommended'],
    workflows: ['KPI aggregation', 'Trend analysis', 'Cross-module attribution', 'Cohort analysis', 'Forecasting'],
    permissions: ['owner', 'admin', 'manager', 'analyst', 'viewer'],
    analytics: ['Views', 'Saves', 'Directions', 'RSVPs', 'Attendance', 'Redemptions', 'CTR', 'Activation Rate', 'Retention', 'Growth'],
    apiSurface: ['/api/insights/overview', '/api/insights/trends', '/api/insights/top-perks'],
    automations: [
      {
        trigger: 'KPI threshold crossed',
        condition: 'Metric is materially above or below baseline',
        action: 'Create recommended action',
        notification: 'Notify analytics owner',
        auditLog: 'analytics_recommendation_created',
      },
    ],
    agent: {
      name: 'Analytics Copilot',
      responsibilities: ['Cross-module search', 'Performance diagnosis', 'Forecasting', 'Opportunity detection', 'Operational recommendations'],
      examplePrompts: ['Which offers drove the most redemptions?', 'Which building has the highest engagement?', 'What should we launch next month?'],
    },
  },
  {
    id: 'automation',
    route: '/admin/dashboard',
    productName: 'Automation + Agent Layer',
    label: 'Automation',
    positioning: 'Trigger, condition, action, notification, audit log.',
    purpose: 'Coordinates workflow execution, agent recommendations, scheduled jobs, notifications, and auditability across every domain.',
    icon: Workflow,
    capabilities: ['workflow', 'permissions', 'automation', 'analytics', 'api', 'agent'],
    coreObjects: ['Trigger', 'Condition', 'Action', 'Notification', 'Audit Log', 'Workflow Run', 'Agent Task'],
    states: ['Draft', 'Active', 'Paused', 'Failed', 'Completed', 'Archived'],
    lifecycle: ['Trigger Fired', 'Condition Evaluated', 'Action Run', 'Notification Sent', 'Audit Logged'],
    workflows: ['Monthly reports', 'Survey escalation', 'Resident reactivation', 'Offer review', 'Partner onboarding'],
    permissions: ['owner', 'admin', 'manager', 'analyst'],
    analytics: ['Workflow runs', 'Failure rate', 'Notification success', 'Tasks created', 'Agent recommendations accepted'],
    apiSurface: ['/api/platform', '/api/functions/*', '/api/entities/ManagementNotification'],
    automations: [
      {
        trigger: 'Any domain event',
        condition: 'Configured workflow matches event payload',
        action: 'Execute action sequence',
        notification: 'Notify owner or affected party',
        auditLog: 'workflow_run_completed',
      },
    ],
    agent: {
      name: 'Downtown Perks Intelligence Layer',
      responsibilities: ['Cross-module search', 'Cross-module reporting', 'Recommendations', 'Forecasting', 'Operational insights', 'Automation orchestration'],
      examplePrompts: ['What needs attention today?', 'Which workflow should be automated next?'],
    },
  },
];

export const enterpriseComponents: EnterpriseComponent[] = [
  { name: 'Billing', requirement: 'Stripe subscriptions, invoices, package entitlement checks, and payment-to-workspace activation.', status: 'required' },
  { name: 'Identity', requirement: 'Auth, RBAC, SSO, organization memberships, invites, and workspace switching.', status: 'foundation' },
  { name: 'Audit Logs', requirement: 'Every operational action should be recorded with actor, resource, scope, and timestamp.', status: 'partial' },
  { name: 'Notifications', requirement: 'Email, SMS, push, in-app, escalation rules, retries, and delivery logs.', status: 'partial' },
  { name: 'Document Storage', requirement: 'Persistent report, export, invoice, and attachment storage.', status: 'required' },
  { name: 'Workflow Engine', requirement: 'Trigger, condition, action, notification, audit-log backbone for every module.', status: 'foundation' },
  { name: 'API Layer', requirement: 'Public and internal APIs with tenant isolation and stable domain contracts.', status: 'foundation' },
  { name: 'Integration Layer', requirement: 'Google, Stripe, Twilio, HubSpot, calendar, sheets, and webhook adapters.', status: 'partial' },
  { name: 'Suggestions Layer', requirement: 'Helpful prompts, task queue, approval gates, and insight logs.', status: 'foundation' },
  { name: 'Data Warehouse', requirement: 'Unified analytics source of truth for residents, buildings, partners, events, offers, and surveys.', status: 'required' },
  { name: 'Observability', requirement: 'Runtime logs, health checks, errors, monitoring, workflow alerts, and deployment traces.', status: 'partial' },
];

export const platformArchitecture = {
  layers: ['Identity Layer', 'Resident OS', 'Property OS', 'Partner OS', 'Events OS', 'Perks OS', 'Engagement OS', 'Survey OS', 'Reporting OS', 'Analytics OS', 'Automation + Agent Layer'],
  operatingLoop: ['Find it', 'Take part', 'See what happened', 'Share the result', 'Act'],
  automationFramework: ['Trigger', 'Condition', 'Action', 'Notification', 'Audit Log'],
  masterAgent: {
    name: 'Downtown Perks Intelligence Layer',
    icon: Bot,
    responsibilities: ['Cross-module search', 'Cross-module reporting', 'Recommendations', 'Forecasting', 'Operational insights', 'Automation orchestration'],
  },
  platformCoverage: {
    currentEstimate: '25-30%',
    target: 'Production SaaS operating system',
    nextFoundations: ['Domain-driven module architecture', 'State machines', 'Workflow engine', 'Agent framework', 'Event bus', 'Audit layer', 'Billing layer', 'Notification layer', 'Unified analytics warehouse'],
  },
};

export const platformSummaryCards = [
  { label: 'Platform Domains', value: platformDomains.length, icon: Database },
  { label: 'Module Agents', value: platformDomains.filter((domain) => domain.agent).length, icon: Bot },
  { label: 'Automations', value: platformDomains.reduce((sum, domain) => sum + domain.automations.length, 0), icon: Bell },
  { label: 'Core Objects', value: platformDomains.reduce((sum, domain) => sum + domain.coreObjects.length, 0), icon: Activity },
];

export function serializePlatformDomain(domain: PlatformDomain) {
  const { icon, ...serializable } = domain;
  return serializable;
}
